windows popup
alizaamir123/mobile-version pull request #14
Opened 2023-05-24 15:58 UTC by alizaamir123

##In this PR:
When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
When the user clicks (or taps) the close (X) button, the popup disappears.
You need to use a JavaScript array to store all of the information for all projects.

2023-05-24 16:23 UTC, Zuhaib042 reviewed
Hi @alizaamir123 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is a pair programming activity and I don't see any commit from your partner. kindly consider getting commit from your partner as actual code not just some changes in readme.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-26 21:32 UTC, vickymarz requested changes
Hi @alizaamir123, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the Git Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️
_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-26 21:32 UTC, vickymarz commented on Js/popup.js
> +       <img class="img pop-image" src="${data.popimage}" alt="">
- [ ] Kindly fix the image overstretch on all your popup cards for the desktop view. You can fix this by removing the fixed height you added for the images.
your image 👇🏽 
![image](https://github.com/alizaamir123/mobile-version/assets/63473584/d2bb13af-46fc-4ba2-8228-45308b60d354)
 
figma image 👇🏽 
![image](https://github.com/alizaamir123/mobile-version/assets/63473584/8b1cea15-6867-4bf1-ae3a-5814b876cca0)

2023-05-26 21:32 UTC, vickymarz commented on Js/popup.js
> +  popopcontainer.innerHTML = ` <div class="container-popup">
- [ ] Some content on your popup seems to be chopped off on both mobile and desktop views. I think you can fix this by removing the margin-bottom of the container ad setting the popup min-height to 100%

![image](https://github.com/alizaamir123/mobile-version/assets/63473584/37f7389b-5289-45c3-9c95-a11fdb9c340d)

2023-05-27 00:36 UTC, jmonto55 approved these changes
# STATUS: APPROVED 🟢

Hi @alizaamir123 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![AgreeSealGIF](https://user-images.githubusercontent.com/116701485/232347692-8a213af9-b250-4d2c-a690-7f42d3c630e0.gif)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-27 09:43 UTC, merged