Contact me
alizaamir123/mobile-version pull request #4
Opened 2023-05-03 11:03 UTC by alizaamir123

In this PR: 
Add contact us form in index.html file
and give styling in style.css file

2023-05-03 11:08 UTC, Ibizugbe reviewed
Hi Team👋👋, 

![INVALID](https://user-images.githubusercontent.com/64643995/235899495-05bb4e7e-2c01-407b-84a3-28ea24383d85.gif)


While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has some linter checks failing🥲. Your stylint check is currently failing, kindly fix the issue and resubmit your project👍.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-03 11:49 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 11:49 UTC, Qoosim commented on index.html
> +  <form action="#" method="post">
- [ ] It is required to integrate your for with formspree service where the `action` atttibute in your form would point to. You must create an account on the [formspree](https://formspree.io/html/) site where you would be given an id that will be used in your form. the action attribute on your form will look like this :point_down: 

```
  <form action="https://formspree.io/f/{form_id}" method="post">
```
Kindly work on that.

2023-05-03 11:49 UTC, Qoosim commented on index.html
> +</div>
- [ ] It is required to stick to the design as close as possible. This simply means that, you're expected to produce a close replica of the design. At this moment, your design does not look like how it is on the Figma design. Kindly look into the contact me section on the Figma design and work your design alongside that design.

### Your Design
![your-design](https://user-images.githubusercontent.com/26597432/235907502-11bf9c33-3aba-4b71-94f2-feb6493358f7.png)

### Figma Design
![temp-design](https://user-images.githubusercontent.com/26597432/235907523-ca3f757d-0f76-477e-b312-dc2e381061e7.png)

2023-05-03 12:09 UTC, ShadyShawkat approved these changes
## Hi @alizaamir123, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- All linters are passing ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 00:27 UTC, Tufahel requested changes
Hi @alizaamir123, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code. 

## Invalid Code Review Request

You have submitted the wrong pull request.

According to the [project requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/4_desktop_version.md) you need to submit a pull request with the implementation of the portfolio desktop version.

- [ ] Kindly open a new pull request with the implementation of the desktop version of the portfolio and ask review again.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-06 11:15 UTC, merged